name: Mise a jour Prix RAM
on:
  schedule:
    - cron: '*/5 * * * *' # Check toutes les 5 minutes
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    # --- LA COMMANDE PRO POUR FORCER NODE.JS 24 ---
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      
    steps:
      - name: Recuperer le code (Version Node 24 Ready)
        uses: actions/checkout@v4

      - name: Installer Python (Version Node 24 Ready)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installer Playwright, Chrome ET les dependances systeme (LOCK IN)
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install --with-deps chromium

      - name: Lancer le robot
        run: python robot.py

      - name: Sauvegarder les changements
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add data.json
          git commit -m "MAJ Prix Auto" || exit 0
          git push
